ika-rwth-aachen/docker-ros

- .gitlab-ci/docker-ros.yml
- docker/entrypoint.sh
- fix default command for run images, build with gitlab ci
- fix handling of `${CI_RUNNER_EXECUTABLE_ARCH}` (default runner architecure) by checking the platform variable in job:script instead of job:rule
- improve entrypoint analogous to https://github.com/ika-rwth-aachen/docker-ros-ml-images/pull/1
> Fix bug in gitlab run images

- .github/workflows/gitlab.yml
- .gitlab-ci/docker-ros.yml
- README.md
- `PLATFORM` defaults to `$CI_RUNNER_ARCH` in GitLab
- `$CI_RUNNER_ARCH` cannot be checked in `rules:`, as it is only populated once a GitLab runner picks the job
- that's why we are currently always starting `arm64` jobs, even if disabled, and then do nothing in those jobs
- at least two problems arise
- pipeline fails if no `arm64` runners are available
- push job also defaults to only push `$CI_RUNNER_ARCH`, thereby currently breaking the multiarch images
- let `PLATFORM` default to `amd64`
- use `rules:` to check whether jobs needs to be added to the pipeline
> Fix platform issues in GitLab

- .gitlab-ci/docker-ros.yml
- if only one platform/arch is enabled, final images are not pushed as manifest lists anymore
- this allows to later amend them to other manifest lists
- no changes for GitHub action, since that one does not yet have manifest support
> [GitLab] Push regular images instead of manifest in case of single arch

- README.md
- docker/Dockerfile
- docker/recursive_vcs_import.py
Always installing `ros-${ROS_DISTRO}-ros-core` and sourcing ROS before `rosdep` ensures that `ROS_VERSION` is set for every base-image (especially for using non-ROS base-images) and that standard ROS2 CLI tools like `rosrun` are always installed.
> Fix rosdep install for non-ROS base images

- .github/workflows/github.yml
- .github/workflows/gitlab.yml
- docker/Dockerfile
This fixes library incompatibilities while installing dependencies
> Dockerfile: Check ROS_VERSION when adding repos

- docker/Dockerfile
If the ENABLE_RECURSIVE_VCS_IMPORT flag is set to false, then the repository in .repos is not recursively imported, which is necessary when working with submodules.
> Include submodules when using vcs import

- docker/recursive_vcs_import.py
If an upstream repo specified in .repos contains itself an empty .repos file, `vcs import` fails, making it impossible to clone the repo.
Example: Running `vcs import` on https://github.com/tier4/ars408_driver/tree/main results in the error `Input data is not valid format: 'NoneType' object is not subscriptable`.
While technically an empty .repos file is invalid, those cases can easily ignored for the ease-of-use.
> Ignore empty .repos files in recursive VCS import

- action.yml
If the GitHub username contains upper-case characters, the docker-ros action fails because the default image name is not lower-case, although that is required.
See also https://github.com/orgs/community/discussions/25768.
This ensures that the default image name is converted into a lower-case string.
> Enforce lower-case image name in GitHub Action

- docker/Dockerfile
- containers take long to shut down
- reason is that `docker stop` sends `SIGTERM` signal
- [ROS listens for SIGINT](https://wiki.ros.org/roscpp/Overview/Initialization%20and%20Shutdown)
- after 10s, container is killed via `SIGKILL`
- use `tini` as init process: [Why tini?](https://github.com/krallin/tini?tab=readme-ov-file#why-tini)
- [Why Your Dockerized Application Isn’t Receiving Signals](https://hynek.me/articles/docker-signals/)
- correctly forwards signals and speeds up container shutdown
- alternatives
- `stop_signal: SIGINT` in Docker Compose: works for speeding up shutdown of ROS apps, but doesn't bring tini benefits
- `docker run --init`: automatically starts containers with tini; works for speeding up shutdown, but is easily forgotten
---
```yml
services:
current:
image: …
```
> Add tini as PID 1 process in front of entrypoint

- docker/Dockerfile
- avoid printing `(alternatives 1/1)`
before (example):
```bash
#[apt] Installation commands:
apt-get install -y ros-jazzy-rviz2
'apt-get install -y libqt5gui5t64' (alternative 1/1)
```
after (example):
```bash
#[apt] Installation commands:
apt-get install -y ros-jazzy-rviz2
apt-get install -y libqt5gui5t64
```
> Improve rosdep simulate output

- .github/workflows/github.yml
- .github/workflows/gitlab.yml
- LICENSE
- README.md
- docker/Dockerfile
- docker/entrypoint.sh
- deal with new pip warning ([see here](https://stackoverflow.com/questions/75602063/pip-install-r-requirements-txt-is-failing-this-environment-is-externally-mana))
- check if new user exists in entrypoint to enable re-starting container without removal
- [see here](https://github.com/ika-rwth-aachen/docker-ros-ml-images/pull/5)
- ROS distro badges
- license updates
- contact text updated
- docker-ros-ci fixed by generating new GitLab token to read pipeline status
- CI now restricted to push to main and pull request to main to avoid duplicate pipelines
> ROS 2 Jazzy Ubuntu 24.04 support | Entry point user/group check | README updates | CI fixes

- docker/Dockerfile
- Uses `pip config` command to edit `/root/.config/pip/pip.conf`
- https://pip.pypa.io/en/latest/cli/pip_config/
- No more collisions possible
- Previous behavior: Possibly two sections `[global]` in  `/root/.config/pip/pip.conf` would have been created which causes pip to crash
Note that
```
#
#
```
Hence we need to execute:
```docker
RUN python -m pip config --global set global.break-system-packages true
```
> Use build-in modification of pip.conf

- .gitlab-ci/docker-ros.yml
- docker/Dockerfile
The ROS keyring file is only installed if it does not already exist due to an already installed ROS version.
> Align ROS keyring with official ROS Docker images

- .github/workflows/gitlab.yml
- update version for `download-artifact` and `upload-artifact` to `v4`
- due to security reasons (https://github.com/ika-rwth-aachen/docker-ros/security/dependabot/1)
> Update artifact action versions

- README.md
- docker/Dockerfile
- docker/entrypoint.sh
- adds support for using `rmw_zenoh`
- only works for distros: `rolling`, `iron` and `jazzy` (restricted by zenoh)
- tested with simple talker / listener demo
> Support usage of `rmw_zenoh`

- .gitlab-ci/docker-ros.yml
- action.yml
Hotfix after https://github.com/ika-rwth-aachen/docker-ros/pull/34
> Ignore RMW_IMPLEMENTATION for industrial_ci to avoid error if zenoh is used

- scripts/ci.sh
- #33 has integrated built-in support for slim. A hotfix is required to run slim in GitHub jobs that build multiarch images, i.e., `platforms: amd64,arm64` and `enable-singlearch-push: false`.
- Currently, the lines responsible for pushing the slimmed image cannot handle multiarch-tags, see [this mqtt_client action log](https://github.com/ika-rwth-aachen/mqtt_client/actions/runs/11554064275).
- The fix is to re-run slim in the second `push` execution of `ci.sh`, where platforms are not treated separately anymore. A current shortcoming is that slim is then only executed for the native platform, i.e., `amd64` in most cases. You would end up with `latest` (multiarch) and `latest-slim` (singlearch).
- A successful [mqtt_client action log is found …
> Fix slim integration for multiarch builds in GitHub CI

- README.md
- docker/Dockerfile
- docker/entrypoint.sh
The following modifications are necessary to enable the usage of docker-ros-generated images, which already have their install space and their src folder, as base images for docker-ros:
- Create new bash script .install-dependencies.sh for a newly started pipeline run instead of appending an existing one. 
- If the install space already exists in the scope of the base image (docker-ros-generated), move this install space in order to make space for a new one.
- Remove potentially existing src folder which might exist in the scope for the base image (docker-ros-generated).
- Source from both, from the moved install space coming from the base image (docker-ros-generated) and from the newly created install space.
> Fix workspace such that docker-ros-generated images can be used as base images for docker-ros

- .gitlab-ci/docker-ros.yml
- README.md
- action.yml
- docker/Dockerfile
- set default `rmw-zenoh-git-ref` to https://github.com/ros2/rmw_zenoh/commit/a7187eb42fd6a6a6bdfacf4308add39e5d8a27c7
- the previous default (https://github.com/ros2/rmw_zenoh/commit/28d917e0532fed6e9703f044662298f2b3553716) does no longer belong to any branch (seems to be foce-pushed)
- in addition, the behavior of `rosdep update || true` is fixed / improved
> Update default `rmw-zenoh-git-ref`

- docker/entrypoint.sh
- make chown in entrypoint safe from existing uid/gid
- add warnings if uid/gid is already existing
> Improve entrypoint

- .gitlab-ci/docker-ros.yml
- README.md
- action.yml
- docker/Dockerfile
In the [rmw_zenoh repo](https://github.com/ros2/rmw_zenoh), the separation between rolling / humble and jazzy has been made. Using the latest version of each branch fixes errors that still occur. E.g. timestamps in bag files.
Once zenoh is available on apt, the build-from-src should be discarded (but: think about jazzy ubuntu22 images).
> Defaultly use latest distro branch as zenoh ref

- .gitlab-ci/docker-ros.yml
- README.md
- action.yml
- docker/Dockerfile
- switch default of `RMW_IMPLEMENTATION` back to `rmw_fastrtps_cpp`
- reason is that FastRTPS is still the ROS 2 default DDS implementation
- related to https://github.com/ika-rwth-aachen/docker-ros/pull/19
> Change RMW default to rmw_fastrtps_cpp

- docker/Dockerfile
- add `PIP_BREAK_SYSTEM_PACKAGES=1` to rosdep command
> Allow rosdep to break system packages for pip dependencies

- docker/Dockerfile
When installing the additional pip and deb requirements, adding a comment line is really useful for us. But current script throws an error when doing so and considers the commented line as a package.
> fixing errors when adding comment lines in additional installs
